records:
  - type: Ref
    name: customer
    count: 12
    schema:
      - name: cust_id
        namespace: datatype
        unique: true
        function: number
        args: [{"min":0,"max":10}]
      - name: firstname
        namespace: name
        function: firstName
        args: [1]
      - name: lastname
        namespace: name
        function: lastName
  - type: Ref
    name: product
    count: 10
    schema:
      - name: product_name
        namespace: commerce
        unique: true
        function: productName
      - name: price
        namespace: commerce
        function: price       
  - type: Master
    schema:
      - name: customer
        namespace: ref
        function: customer
      - name: product
        namespace: ref
        function: product
      - name: quantity
        namespace: datatype
        function: number
        args: [{"min":20,"max":50}]
