records:
  - type: Source
    count: 10
    schema:
      - name: id
        namespace: datatype
        unique: true
        function: number
        args: [{"min":1000,"max":9999}]
      - name: base
        namespace: datatype
        function: number
        args: [{"min":110,"max":135}]
  - type: Master
    schema:
      - name: variation
        namespace: datatype
        function: number
        args: [{"min":-7,"max":7}]
      - name: isanomaly
        namespace: datatype
        function: number
        args: [{"min":1,"max":1}]
        anomaly:
          magnitude: 5
          frequency: 1

