records:
  - type: Master
    schema:
      - name: user
        namespace: datatype
        function: number
        args: [{"min":0,"max":3}]
      - name: item
        namespace: helpers
        function: randomize
        args: [["itemA","itemB","itemC"]]
      - name: quantity
        namespace: datatype
        function: number
        args: [{"min":-10,"max":10}]
